In [2]:
import pandas as pd
import numpy as np
import math

In [2]:
# VODS disciplines codes:
discipline_codes=['0101',
'0102',
'0103',
'0104',
'0105',
'0106',
'0107',
'0199',
'0201',
'0202',
'0203',
'0204',
'0205',
'0206',
'0207',
'0208',
'0299',
'0301',
'0302',
'0303',
'0304',
'0305',
'0306',
'0399',
'0401',
'0402',
'0499',
'0501',
'0502',
'0503',
'0504',
'0505',
'0506',
'0507',
'0508',
'0599',
'0601',
'0602',
'0603',
'0604',
'0699',
'0700']

In [3]:
# VODS disciplines names:
discipline_names =['Mathematical sciences',
'Information and computing sciences',
'Physical sciences',
'Chemical sciences',
'Earth sciences',
'Biological sciences',
'Environmental sciences',
'Other natural sciences',
'Civil and building engineering',
'Electrical and electronic engineering',
'Mechanical and manufacturing engineering',
'(Bio)chemical engineering',
'Materials engineering',
'(Bio)medical engineering',
'Biotechnology, bio-engineering and biosystems engineering',
'Computer engineering, information technology and mathematical engineering',
'Other engineering and technology',
'Basic sciences',
'Clinical sciences',
'Health sciences',
'Paramedical sciences',
'Pharmaceutical sciences',
'Translational sciences',
'Other medical and health sciences',
'Agriculture, forestry, fisheries and allied sciences',
'Veterinary sciences',
'Other agricultural, veterinary and food sciences',
'Psychology and cognitive sciences',
'Economics and business',
'Pedagogical and educational sciences',
'Sociology and anthropology',
'Law and legal studies',
'Political sciences',
'Social and economic geography',
'Media and communications',
'Other social sciences',
'History and archaeology',
'Languages and literary studies',
'Philosophy, ethics and religious studies',
'Arts',
'Other humanities and the arts',
'General and logistic services']

# Uniform distance matrix

In [4]:
np.savetxt('uniform_distance_matrix.txt', np.ones((42,42))-np.identity(42))

# All matrices (also non-symmetric)

## Cosine salton normalization

In [3]:
count_type = 'citation_flow'
data = 'matrix15'
count_type = 'disc_in_a_person'
data = 'pub_2014'
count_type = 'colab'
data = 'projects'

df = pd.read_table(count_type+'_'+data+'.txt', delim_whitespace=True, header=None)
nb_of_disciplines = df.shape[0]  # 42


cosine_sim_matrix=np.zeros((nb_of_disciplines, nb_of_disciplines))


for i in range(nb_of_disciplines):
    df.iloc[i,i]=sum(df.iloc[:,i])


for i in range(nb_of_disciplines):
    for j in range(nb_of_disciplines):
        if sum(df.iloc[:,i]) == 0 or sum(df.iloc[:,j]) == 0:
            if i == j:
                cosine_sim_matrix[i,j]=1
            else:
                cosine_sim_matrix[i,j]=0
        else:         
            cosine_sim_matrix[i,j] = np.inner(df.iloc[:,i],df.iloc[:,j])/(np.inner(df.iloc[:,j],df.iloc[:,j])**(1/2)* np.inner(df.iloc[:,i],df.iloc[:,i])**(1/2))


cosine_distance_matrix=np.round(1-cosine_sim_matrix,10)

# np.savetxt('dm_cosine_' + count_type + '_' + data+  '.txt', cosine_distance_matrix)
np.savetxt('sm_cosine1_' + count_type + '_' + data+  '.txt', 1-cosine_distance_matrix)
cosine_distance_matrix

array([[-0.        ,  0.72624077,  0.88045115, ...,  0.97851271,
         0.98528491,  0.96671073],
       [ 0.72624077,  0.        ,  0.93020018, ...,  0.96444668,
         0.96787335,  0.97621954],
       [ 0.88045115,  0.93020018, -0.        , ...,  0.99111668,
         0.99440941,  0.95832925],
       ...,
       [ 0.97851271,  0.96444668,  0.99111668, ...,  0.        ,
         0.7982337 ,  0.95482778],
       [ 0.98528491,  0.96787335,  0.99440941, ...,  0.7982337 ,
         0.        ,  0.97593248],
       [ 0.96671073,  0.97621954,  0.95832925, ...,  0.95482778,
         0.97593248,  0.        ]])

In [6]:
count_type = 'disc_in_a_person'
data = 'pub_2014'
df = pd.read_table(count_type+'_'+data+'.txt', delim_whitespace=True, header=None)
df
for i in range(42):
    som=0
    for j in range(42):
        if j ==i:
            continue
        som=som+df.iloc[i,j]
    print(df.iloc[i,i]- som)

-423.0
-3015.0
481.0
-1581.0
-1393.0
-4857.0
-1327.0
393.0
-203.0
-211.0
2.0
63.0
-2858.0
-4986.0
-3451.0
-3498.0
-1796.0
-8141.0
-5402.0
-5167.0
-4191.0
44.0
-8500.0
-2863.0
-1446.0
-556.0
-524.0
445.0
590.0
-280.0
-828.0
1284.0
-488.0
-1020.0
-567.0
-543.0
299.0
718.0
493.0
-4.0
-141.0
32.0


## correlation of columns

In [6]:
count_type = 'citation_flow'
data = 'matrix15'
count_type = 'disc_in_a_person'
data = 'pub_2014'
count_type = 'colab'
data = 'projects'




df = pd.read_table(count_type + '_' + data+'.txt', delim_whitespace=True, header=None)

corr_sim_matrix = np.nan_to_num((df.corr().values+1)/2)
corr_distance_matrix=np.round(1-corr_sim_matrix,10)
for i in range(42):
    corr_distance_matrix[i,i]=0

np.savetxt('dm_corr_' + count_type + '_' + data+  '.txt', corr_distance_matrix)


corr_distance_matrix

array([[0.        , 0.11625639, 0.38099389, ..., 0.54965246, 0.55316559,
        0.50282613],
       [0.11625639, 0.        , 0.44018777, ..., 0.53120136, 0.52393408,
        0.51761526],
       [0.38099389, 0.44018777, 0.        , ..., 0.58061891, 0.57852474,
        0.49933905],
       ...,
       [0.54965246, 0.53120136, 0.58061891, ..., 0.        , 0.10097474,
        0.40567983],
       [0.55316559, 0.52393408, 0.57852474, ..., 0.10097474, 0.        ,
        0.50787798],
       [0.50282613, 0.51761526, 0.49933905, ..., 0.40567983, 0.50787798,
        0.        ]])

# Symmetric matrices

## Jaccard index plus normalization

In [7]:
count_type = 'disc_in_a_person'
data = 'pub_2014'

df = pd.read_table(count_type+'_'+data+'.txt', delim_whitespace=True, header=None)
nb_of_disciplines = df.shape[0]  # 42

jaccard1 = np.zeros((42,42))
for i in range(42):
    jaccard1[i,i] = 1
    for j in range(i):
        jaccard1[i,j]=df.iloc[i,j]/(df.iloc[i,i]+df.iloc[j,j].sum()-df.iloc[i,j])
        jaccard1[j,i]=jaccard1[i,j]
np.savetxt('dm_jaccard_' + count_type + '_' + data+  '.txt',1- jaccard1)
np.savetxt('dm_jaccard_sqrt_' + count_type + '_' + data+  '.txt',1- np.sqrt(jaccard1))


In [5]:
count_type = 'colab'
data = 'projects'
df = pd.read_table(count_type+'_'+data+'.txt', delim_whitespace=True, header=None)
nb_of_disciplines = df.shape[0]  # 42

jaccard = np.zeros((42,42))
for i in range(42):
    jaccard[i,i] = 1
    for j in range(i):
        jaccard[i,j]=df.iloc[i,j]/(df.iloc[i,:].sum()+df.iloc[:,j].sum()-df.iloc[i,j])
        jaccard[j,i]=jaccard[i,j]
np.savetxt('dm_jaccard_' + count_type + '_' + data+  '.txt',1- jaccard)
np.savetxt('dm_jaccard_sqrt_' + count_type + '_' + data+  '.txt', 1- np.sqrt(jaccard))

In [11]:
alpha = np.log(2)/np.log(83)
alpha
np.savetxt('dm_jaccard_sqrt_' + count_type + '_' + data+  '.txt', 1-jaccard**(alpha))

In [13]:
df

0           1           2           3           4            5   \
0   324.536923  267.733670   99.518885   15.147867   29.563939    71.705966   
1   267.733670  729.392254   65.125256   30.263684   19.875472    97.150836   
2    99.518885   65.125256  707.719587  288.747967   75.555409    59.257477   
3    15.147867   30.263684  288.747967  846.881487   63.934038   248.333564   
4    29.563939   19.875472   75.555409   63.934038  207.834805   130.923157   
5    71.705966   97.150836   59.257477  248.333564  130.923157  1339.682100   
6    24.319468   20.600989   35.467744   79.450019  105.821764   384.505233   
7    14.574002   10.105226   22.585325   18.638056    2.423482    29.284206   
8    32.519120   32.494616    9.399109   12.858050   46.272157    17.380427   
9    45.217747  295.568397  142.153955   99.253073   19.034262    72.377614   
10   31.781063   98.645997   49.782856   48.018428   12.157102    38.300118   
11    7.214317   13.471621   76.943337  327.479773   17.565387    45.053710   
12   14.337613   32.030469  161.833502  236.589430   53.800896    53.718879   
13   10.537255   56.960265   24.473700   88.091067    9.903360   228.265152   
14    8.238002   16.214032   17.978898   93.736336   15.023133   190.319908   
15   28.946804  140.086719   49.854661   21.322048    6.888869    60.949204   
16   29.181153   69.810538   47.988666   29.759868   49.956991    44.736821   
17   30.557874  109.656838   78.441907  212.258601   16.817600   986.611236   
18   18.618332   42.238620   17.397598   57.868466    2.841193   207.907735   
19   43.477210   24.883301    8.937422   13.185408    4.411060    79.162785   
20    8.118497   37.494241    6.016906   30.059298    2.491674    84.022077   
21   13.559458   29.057893   26.506332  294.151866    4.265110   246.357678   
22   23.769332   73.103770   45.639721  153.288450   18.394805   708.303765   
23    2.522705    9.039913    2.312600   10.125611    0.945742    40.778738   
24   27.107516   41.552506    9.794610  129.466347   46.148703   636.148729   
25    6.834248   18.078642    8.643253   27.650950    5.763300   185.289943   
26    0.778365    1.374702    0.461599    8.340976    0.974820    29.693108   
27   67.118275   45.063025   11.894760    7.753748    2.798227    60.855324   
28  122.346499  107.790585   13.097538    8.793307   12.086134    38.558155   
29   26.960379   19.180065   20.865105    5.644056   10.700070    23.552190   
30   12.247703   13.250286    6.912961    2.518224   11.535412    15.385084   
31    6.075673   24.944481    0.000000    1.227116    3.124621     9.758622   
32    5.896343    5.227353    0.555354    0.982625    6.147301     1.672529   
33    7.257942    5.136105    0.941880    0.325821   16.473314     4.130127   
34    3.047711   37.107579    1.760317    0.000000    0.047727    12.084287   
35    3.963619    3.388866    0.296384    0.741035    0.663095     1.291850   
36   12.301400   29.344268    5.189148   28.417742   79.091061    21.055495   
37    7.248630   99.575756    0.487847   12.157407   13.580353     2.398512   
38   14.996503   20.430608   28.915245    5.801047    2.047108    13.335560   
39    6.957385   24.815205    2.469403   11.685990   19.400510    14.822514   
40    0.767991    6.107901    0.238358    1.420872    3.854729     0.890598   
41    3.219841    1.038690    6.488690    3.059280    2.036508     9.087641   

            6          7           8           9   ...          32  \
0    24.319468  14.574002   32.519120   45.217747  ...    5.896343   
1    20.600989  10.105226   32.494616  295.568397  ...    5.227353   
2    35.467744  22.585325    9.399109  142.153955  ...    0.555354   
3    79.450019  18.638056   12.858050   99.253073  ...    0.982625   
4   105.821764   2.423482   46.272157   19.034262  ...    6.147301   
5   384.505233  29.284206   17.380427   72.377614  ...    1.672529   
6   145.477517   6.820924   28.774642   28.960657  ...    7.594271   
7     6.820924   1.385072    1.118580    6.232952  ...

In [16]:
1-0.000027**alpha

0.8079759561218967

In [14]:
pd.DataFrame(jaccard)

0         1         2         3         4         5         6   \
0   1.000000  0.065501  0.027117  0.002975  0.011138  0.008959  0.007780   
1   0.065501  1.000000  0.013030  0.004751  0.005022  0.010477  0.004657   
2   0.027117  0.013030  1.000000  0.052259  0.022783  0.006792  0.009278   
3   0.002975  0.004751  0.052259  1.000000  0.013706  0.025155  0.015531   
4   0.011138  0.005022  0.022783  0.013706  1.000000  0.017301  0.039680   
5   0.008959  0.010477  0.006792  0.025155  0.017301  1.000000  0.049422   
6   0.007780  0.004657  0.009278  0.015531  0.039680  0.049422  1.000000   
7   0.008538  0.003363  0.009384  0.004974  0.001807  0.004367  0.003782   
8   0.010331  0.007316  0.002423  0.002467  0.016787  0.002125  0.008880   
9   0.010273  0.054284  0.028360  0.015527  0.004700  0.007709  0.006426   
10  0.009052  0.020822  0.011851  0.008669  0.003856  0.004496  0.002941   
11  0.002334  0.003077  0.020633  0.068008  0.006498  0.005585  0.007837   
12  0.003841  0.006395  0.037698  0.042591  0.016227  0.006169  0.005011   
13  0.002880  0.011610  0.005622  0.015658  0.003018  0.026996  0.007574   
14  0.002703  0.003741  0.004799  0.018720  0.005640  0.024151  0.017172   
15  0.010950  0.036616  0.014970  0.004541  0.003011  0.007993  0.004235   
16  0.010165  0.016929  0.013480  0.006055  0.020206  0.005685  0.012433   
17  0.002837  0.009149  0.006862  0.016800  0.001616  0.066530  0.002579   
18  0.004213  0.007425  0.003393  0.009008  0.000700  0.022492  0.002694   
19  0.014107  0.005663  0.002337  0.002557  0.001608  0.009821  0.004715   
20  0.002177  0.007508  0.001355  0.005226  0.000742  0.009693  0.001282   
21  0.003073  0.005106  0.005189  0.047621  0.001055  0.026794  0.005049   
22  0.002731  0.007350  0.004861  0.014438  0.002208  0.054352  0.002697   
23  0.001256  0.002743  0.000851  0.002503  0.000579  0.005838  0.000672   
24  0.005297  0.006496  0.001676  0.018339  0.009776  0.066803  0.045356   
25  0.002873  0.004938  0.002802  0.006280  0.002878  0.025681  0.011674   
26  0.000451  0.000455  0.000190  0.002216  0.000723  0.004424  0.002829   
27  0.013967  0.007362  0.002136  0.001122  0.000623  0.006193  0.000532   
28  0.027686  0.018821  0.002501  0.001337  0.002911  0.004051  0.014352   
29  0.008241  0.004194  0.005235  0.001057  0.003677  0.002841  0.004168   
30  0.003559  0.002799  0.001664  0.000458  0.003764  0.001820  0.003892   
31  0.001871  0.005517  0.000000  0.000232  0.001088  0.001182  0.002374   
32  0.001937  0.001205  0.000148  0.000193  0.002305  0.000207  0.002425   
33  0.003661  0.001567  0.000349  0.000081  0.010323  0.000590  0.008916   
34  0.001403  0.010812  0.000611  0.000000  0.000027  0.001684  0.002776   
35  0.002106  0.001067  0.000114  0.000189  0.000440  0.000187  0.001274   
36  0.003563  0.006205  0.001245  0.005184  0.026290  0.002489  0.008254   
37  0.002049  0.021011  0.000115  0.002180  0.004306  0.000280  0.002002   
38  0.004938  0.004724  0.007750  0.001140  0.000766  0.001656  0.000679   
39  0.002267  0.005712  0.000653  0.002287  0.007242  0.001836  0.007992   
40  0.000413  0.001939  0.000093  0.000364  0.002603  0.000130  0.000690   
41  0.001804  0.000337  0.002606  0.000799  0.001446  0.001338  0.001511   

          7         8         9   ...        32        33        34        35  \
0   0.008538  0.010331  0.010273  ...  0.001937  0.003661  0.001403  0.002106   
1   0.003363  0.007316  0.054284  ...  0.001205  0.001567  0.010812  0.001067   
2   0.009384  0.002423  0.028360  ...  0.000148  0.000349  0.000611  0.000114   
3   0.004974  0.002467  0.015527  ...  0.000193  0.000081  0.000000  0.000189   
4   0.001807  0.016787  0.004700  ...  0.002305  0.010323  0.000027  0.000440   
5   0.004367  0.002125  0.007709  ...  0.000207  0.000590  0.001684  0.000187   
6   0.003782  0.008880  0.006426  ...  0.002425  0.008916  0.002776  0.001274   
7   1.000000  0.000608  0.002010  ...  0.000229  0.000610  0.000100  0.000421   
8   0.000608

## Sorensen Dice Coefficient

In [26]:
count_type = 'colab'
data = 'projects'
df = pd.read_table(count_type+'_'+data+'.txt', delim_whitespace=True, header=None)
nb_of_disciplines = df.shape[0]  # 42
df= df+1


sdc = np.zeros((42,42))
for i in range(42):
    sdc[i,i] = 1
    for j in range(i):
        sdc[i,j]=(2*df.iloc[i,j])/(df.iloc[i,:].sum()+df.iloc[:,j].sum())
        sdc[j,i]=sdc[i,j]
np.savetxt('dm_sdc_' + count_type + '_' + data+  '.txt', -np.log(sdc)/np.log(42))
np.savetxt('sm_sdc_' + count_type + '_' + data+  '.txt', sdc)

In [47]:
df.values.sum()/2+np.diag(df.values).sum()/2

55885.99999999981

In [29]:
np.diag(df.values).sum()

20187.935497411578

In [26]:
df.values.sum().sum()-np.diag(df).sum()

69590.12900517648

In [34]:
42*43/2

903.0

In [37]:
np.where(df == 0)

(array([ 2,  3, 11, 11, 11, 21, 26, 26, 26, 26, 26, 26, 26, 26, 31, 31, 33,
        34, 34, 34, 34, 35, 35, 36, 38, 40, 41, 41], dtype=int64),
 array([31, 34, 34, 35, 41, 34, 31, 33, 34, 35, 36, 38, 40, 41,  2, 26, 26,
         3, 11, 21, 26, 11, 26, 26, 26, 26, 11, 26], dtype=int64))

In [6]:
1- sdc

array([[0.        , 0.87705201, 0.94719748, ..., 0.99547623, 0.99917533,
        0.99639879],
       [0.87705201, 0.        , 0.97427436, ..., 0.98864166, 0.99612949,
        0.99932592],
       [0.94719748, 0.97427436, 0.        , ..., 0.99869473, 0.99981453,
        0.99480078],
       ...,
       [0.99547623, 0.98864166, 0.99869473, ..., 0.        , 0.95908805,
        0.99646253],
       [0.99917533, 0.99612949, 0.99981453, ..., 0.95908805, 0.        ,
        0.99789829],
       [0.99639879, 0.99932592, 0.99480078, ..., 0.99646253, 0.99789829,
        0.        ]])

In [15]:
sdc

array([[1.00000000e+00, 1.22947994e-01, 5.28025247e-02, ...,
        4.52377059e-03, 8.24671875e-04, 3.60121344e-03],
       [1.22947994e-01, 1.00000000e+00, 2.57256377e-02, ...,
        1.13583443e-02, 3.87050566e-03, 6.74083459e-04],
       [5.28025247e-02, 2.57256377e-02, 1.00000000e+00, ...,
        1.30526727e-03, 1.85466094e-04, 5.19921704e-03],
       ...,
       [4.52377059e-03, 1.13583443e-02, 1.30526727e-03, ...,
        1.00000000e+00, 4.09119548e-02, 3.53746518e-03],
       [8.24671875e-04, 3.87050566e-03, 1.85466094e-04, ...,
        4.09119548e-02, 1.00000000e+00, 2.10171110e-03],
       [3.60121344e-03, 6.74083459e-04, 5.19921704e-03, ...,
        3.53746518e-03, 2.10171110e-03, 1.00000000e+00]])

In [17]:
sdc[2,31]

0.0

In [19]:
sdc[11,31]

0.0012971808091992683

In [38]:
np.where(sdc == 0)

(array([], dtype=int64), array([], dtype=int64))

In [41]:
(-np.log(sdc)/np.log(42))

array([[-0.        ,  0.56027639,  0.7855656 , ...,  1.42575691,
         1.76556912,  1.46672554],
       [ 0.56027639, -0.        ,  0.97724502, ...,  1.19268273,
         1.46500034,  1.84852766],
       [ 0.7855656 ,  0.97724502, -0.        , ...,  1.72753711,
         1.99642658,  1.38723197],
       ...,
       [ 1.42575691,  1.19268273,  1.72753711, ..., -0.        ,
         0.85170543,  1.47114618],
       [ 1.76556912,  1.46500034,  1.99642658, ...,  0.85170543,
        -0.        ,  1.49102327],
       [ 1.46672554,  1.84852766,  1.38723197, ...,  1.47114618,
         1.49102327, -0.        ]])

## Ochiai Coefficient

In [29]:
count_type = 'colab'
data = 'projects'
df = pd.read_table(count_type+'_'+data+'.txt', delim_whitespace=True, header=None)

ochiai = np.zeros((42,42))
for i in range(42):
    ochiai[i,i] = 1
    for j in range(i):
        ochiai[i,j]=(df.iloc[i,j])/(df.iloc[i,:].sum()*df.iloc[:,j].sum())**(1/2)
        ochiai[j,i]=ochiai[i,j]

np.savetxt('sm_ochiai_' + count_type + '_' + data+  '.txt', ochiai)

In [28]:
ochiai

array([[1.00000000e+00, 1.28758677e-01, 5.37588238e-02, ...,
        4.52381932e-03, 1.07773391e-03, 5.12966477e-03],
       [1.28758677e-01, 1.00000000e+00, 2.58995522e-02, ...,
        1.18788842e-02, 6.31023962e-03, 1.21825787e-03],
       [5.37588238e-02, 2.58995522e-02, 1.00000000e+00, ...,
        1.32776288e-03, 2.76601189e-04, 8.54832209e-03],
       ...,
       [4.52381932e-03, 1.18788842e-02, 1.32776288e-03, ...,
        1.00000000e+00, 5.36266986e-02, 5.05556942e-03],
       [1.07773391e-03, 6.31023962e-03, 2.76601189e-04, ...,
        5.36266986e-02, 1.00000000e+00, 2.11864855e-03],
       [5.12966477e-03, 1.21825787e-03, 8.54832209e-03, ...,
        5.05556942e-03, 2.11864855e-03, 1.00000000e+00]])

In [4]:
count_type = 'disc_in_a_person'
data = 'pub_2014'
df = pd.read_table(count_type+'_'+data+'.txt', delim_whitespace=True, header=None)
ochiai = np.zeros((42,42))
for i in range(42):
    ochiai[i,i] = 1
    for j in range(i):
        ochiai[i,j]=(df.iloc[i,j])/(df.iloc[i,i]*df.iloc[j,j])**(1/2)
        ochiai[j,i]=ochiai[i,j]

np.savetxt('sm_ochiai_' + count_type + '_' + data+  '.txt', ochiai)

In [29]:
count_type = 'colab'
data = 'projects'
df = pd.read_table(count_type+'_'+data+'.txt', delim_whitespace=True, header=None)
df
df.sum()

0     1530.823227
1     2824.411240
2     2238.651274
3     3575.428998
4     1153.174402
5     6545.098655
6     1619.496108
7      190.648156
8     1649.546328
9     2915.977708
10    2011.843273
11    1567.393707
12    2216.123432
13    2138.658549
14    1525.565310
15    1141.560543
16    1369.201104
17    9271.185866
18    2906.629742
19    1594.655494
20    2206.932349
21    2895.654669
22    7195.104461
23     480.445366
24    3613.816185
25     855.149001
26     197.009318
27    3341.897755
28    3010.613089
29    1767.728934
30    1922.826434
31    1721.790527
32    1519.759022
33     459.119836
34     644.918726
35     355.098967
36    1934.304954
37    2014.479785
38    1521.153166
39    1545.099679
40     331.714429
41     257.374736
dtype: float64

In [28]:
[discipline_codes[i] for i in np.where(df.sum()<500)[0]]

['0199', '0399', '0499', '0507', '0599', '0699', '0700']

In [18]:
count_type = 'disc_in_a_person'
data = 'pub_2014'
df = pd.read_table(count_type+'_'+data+'.txt', delim_whitespace=True, header=None)
df.sum()

0      6841.0
1      9887.0
2      4331.0
3      9899.0
4      4505.0
5     21511.0
6      5801.0
7      2729.0
8      4293.0
9      7385.0
10     4898.0
11     2625.0
12     8620.0
13    12338.0
14     7867.0
15     9896.0
16     7088.0
17    32067.0
18    18186.0
19    13121.0
20    15237.0
21     3940.0
22    30308.0
23     9669.0
24     8862.0
25     3764.0
26     2872.0
27     4845.0
28     6166.0
29     4192.0
30     5262.0
31     2144.0
32     3254.0
33     3738.0
34     3643.0
35     4603.0
36     2173.0
37     2894.0
38     1449.0
39     3086.0
40     2499.0
41      172.0
dtype: float64

## probabilistic activity index (PAI)

In [30]:
count_type = 'colab'
data = 'projects'
df = pd.read_table(count_type+'_'+data+'.txt', delim_whitespace=True, header=None)
total_sum = df.sum().sum()

pai = np.zeros((42,42))
for i in range(42):
    for j in range(42):
        pai[i,j]=df.iloc[i,j]*total_sum/(df.iloc[i,:].sum()*df.iloc[:,j].sum())
        
np.savetxt('sm_pai_' + count_type + '_' + data+  '.txt', pai)
pd.DataFrame(pai)


0         1          2         3          4         5         6   \
0   12.433239  5.559302   2.607139  0.248467   1.503531  0.642517  0.880682   
1    5.559302  8.208722   0.924709  0.269052   0.547854  0.471816  0.404343   
2    2.607139  0.924709  12.678228  3.238729   2.627570  0.363087  0.878289   
3    0.248467  0.269052   3.238729  5.947529   1.392128  0.952711  1.231845   
4    1.503531  0.547854   2.627570  1.392128  14.031320  1.557312  5.087101   
5    0.642517  0.471816   0.363087  0.952711   1.557312  2.807628  3.256690   
6    0.880682  0.404343   0.878289  1.231845   5.087101  3.256690  4.979736   
7    4.483234  1.684829   4.750918  2.454766   0.989652  2.106953  1.983357   
8    1.156164  0.626166   0.228510  0.195728   2.183889  0.144527  0.967021   
9    0.909431  3.221930   1.955053  0.854677   0.508191  0.340466  0.550573   
10   0.926445  1.558575   0.992360  0.599316   0.470448  0.261132  0.293411   
11   0.269937  0.273202   1.968687  5.246244   0.872479  0.394282  0.876489   
12   0.379427  0.459422   2.928588  2.680671   1.890039  0.332496  0.478360   
13   0.288956  0.846589   0.458925  1.034267   0.360509  1.464038  0.732291   
14   0.316691  0.337833   0.472624  1.542834   0.766664  1.711226  1.929327   
15   1.487123  3.900680   1.751421  0.468999   0.469812  0.732357  0.565462   
16   1.249915  1.620675   1.405579  0.545765   2.840562  0.448179  1.485989   
17   0.193301  0.375961   0.339310  0.574873   0.141223  1.459704  0.167502   
18   0.375661  0.461915   0.240040  0.499913   0.076100  0.981149  0.231923   
19   1.598969  0.496002   0.224765  0.207620   0.215353  0.680939  0.524407   
20   0.215741  0.540030   0.109337  0.342005   0.087898  0.522226  0.123081   
21   0.274625  0.318977   0.367102  2.550744   0.114672  1.167007  0.434275   
22   0.193743  0.322957   0.254384  0.534951   0.199037  1.350319  0.182657   
23   0.307941  0.598084   0.193037  0.529199   0.153251  1.164243  0.162668   
24   0.439915  0.365488   0.108694  0.899566   0.994188  2.414608  3.483160   
25   0.468699  0.671995   0.405340  0.811915   0.524692  2.972105  1.851145   
26   0.231708  0.221801   0.093964  1.063095   0.385223  2.067392  1.441708   
27   1.177858  0.428617   0.142740  0.058259   0.065188  0.249781  0.043721   
28   2.383317  1.138068   0.174469  0.073340   0.312542  0.175677  1.206325   
29   0.894449  0.344887   0.473357  0.080171   0.471244  0.182755  0.440892   
30   0.373559  0.219042   0.144181  0.032885   0.467055  0.109752  0.395890   
31   0.206947  0.460507   0.000000  0.017896   0.141284  0.077743  0.254832   
32   0.227538  0.109333   0.014655  0.016235   0.314909  0.015096  0.277014   
33   0.927113  0.355590   0.082272  0.017820   2.793381  0.123393  2.218056   
34   0.277149  1.828942   0.109464  0.000000   0.005762  0.257022  0.538866   
35   0.654618  0.303352   0.033473  0.052400   0.145379  0.049902  0.392329   
36   0.372971  0.482215   0.107586  0.368898   3.183301  0.149312  0.833750   
37   0.211027  1.571206   0.009712  0.151538   0.524836  0.016332  0.199766   
38   0.578179  0.426924   0.762321  0.095758   0.104771  0.120252  0.077608   
39   0.264080  0.510509   0.064094  0.189911   0.977534  0.131589  0.900269   
40   0.135780  0.585288   0.028817  0.107556   0.904700  0.036827  0.224681   
41   0.733692  0.128281   1.011055  0.298466   0.616021  0.484328  0.609712   

          7          8         9   ...         32         33         34  \
0   4.483234   1.156164  0.909431  ...   0.227538   0.927113   0.277149   
1   1.684829   0.626166  3.221930  ...   0.109333   0.355590   1.828942   
2   4.750918   0.228510  1.955053  ...   0.014655   0.082272   0.109464   
3   2.454766   0.195728  0.854677  ...   0.016235   0.017820   0.000000   
4   0.989652   2.183889  0.508191  ...   0.314909   2.793381   0.005762   
5   2.106953   0.144527  0.340466  ...   0.015096   0.123393   0.257022   
6   1.983357   0.967021  0.550573  ...   0.277014   2.218056   0.538866   
7   3.421192 

In [23]:
1/(10*28)**(1/2)

0.05976143046671968

In [21]:
pai.sum(axis=0)

array([49.06077868, 44.18167332, 45.72458703, 38.47874017, 52.01860467,
       34.94687204, 43.79720193, 40.60090985, 64.31806761, 42.26271471,
       44.16577372, 42.8657192 , 41.5800855 , 35.04380437, 40.42492885,
       42.86091031, 52.18400113, 28.13734768, 30.95908538, 37.72520662,
       31.71132221, 29.1391961 , 26.30304805, 28.91888542, 44.9205481 ,
       55.78832719, 47.83578984, 36.71103077, 51.42735424, 45.0078354 ,
       60.44080699, 57.21770994, 61.92982704, 65.40382847, 80.13123957,
       68.30337907, 65.99437032, 56.99185942, 60.57205079, 60.38563492,
       67.49806005, 72.95274651])

In [50]:
np.exp(np.log(1/2)*pai)
np.savetxt('dm_pai_' + count_type + '_' + data+  '.txt',np.exp(np.log(1/2)*pai))

In [45]:
cosine_sim_matrix=np.zeros((nb_of_disciplines, nb_of_disciplines))


for i in range(nb_of_disciplines):
    for j in range(nb_of_disciplines):
        if sum(pai_df.iloc[:,i]) == 0 or sum(pai_df.iloc[:,j]) == 0:
            if i == j:
                cosine_sim_matrix[i,j]=1
            else:
                cosine_sim_matrix[i,j]=0
        else:         
            cosine_sim_matrix[i,j] = np.inner(pai_df.iloc[:,i],pai_df.iloc[:,j])/(np.inner(pai_df.iloc[:,j],pai_df.iloc[:,j])**(1/2)* np.inner(pai_df.iloc[:,i],pai_df.iloc[:,i])**(1/2))


cosine_distance_matrix=np.round(1-cosine_sim_matrix,10)

np.savetxt('dm_cosine_pai_' + count_type + '_' + data+  '.txt', cosine_distance_matrix)

corr_sim_matrix = np.nan_to_num((pai_df.corr().values+1)/2)
corr_distance_matrix=np.round(1-corr_sim_matrix,10)
for i in range(42):
    corr_distance_matrix[i,i]=0

np.savetxt('dm_corr_pai_' + count_type + '_' + data+  '.txt', corr_distance_matrix)



jaccard = np.zeros((42,42))
for i in range(42):
    jaccard[i,i] = 1
    for j in range(i):
        jaccard[i,j]=pai_df.iloc[i,j]/(pai_df.iloc[i,:].sum()+pai_df.iloc[:,j].sum()-pai_df.iloc[i,j])
        jaccard[j,i]=jaccard[i,j]
np.savetxt('dm_jaccard_pai_' + count_type + '_' + data+  '.txt',1- jaccard)
np.savetxt('dm_jaccard_sqrt_pai_' + count_type + '_' + data+  '.txt', 1- np.sqrt(jaccard1))

In [39]:
pai_df= pd.DataFrame(pai)
normalize_rows = np.zeros((42,42))
for i in range(42):
    normalize_rows[i,i] = pai_df.iloc[i,i]/max(pai_df.iloc[i,:])
    for j in range(42):
        if i<j:
            normalize_rows[i,j]=pai_df.iloc[i,j]/max(pai_df.iloc[i,:])
        elif i>j:
            normalize_rows[i,j]=pai_df.iloc[i,j]/max(pai_df.iloc[i,:])

np.diag(normalize_rows)

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       0.86211105, 0.97889468, 0.72011168, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.88491102, 1.        , 0.54815296, 0.8840834 , 1.        ,
       1.        , 1.        , 0.53242116, 0.60311347, 0.92242742,
       0.81191428, 0.53385885, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.98242884, 1.        , 1.        , 1.        ,
       1.        , 1.        ])

In [41]:
nz=np.nonzero(np.diag(normalize_rows)-1)
[(discipline_codes[i], discipline_names[i], np.diag(normalize_rows)[i]) for i in list(nz[0])]

[('0106', 'Biological sciences', 0.8621110495181373),
 ('0107', 'Environmental sciences', 0.9788946752692097),
 ('0199', 'Other natural sciences', 0.7201116799409405),
 ('0208',
  'Computer engineering, information technology and mathematical engineering',
  0.884911017227226),
 ('0301', 'Basic sciences', 0.5481529632207701),
 ('0302', 'Clinical sciences', 0.884083396908366),
 ('0306', 'Translational sciences', 0.5324211552793389),
 ('0399', 'Other medical and health sciences', 0.6031134665076054),
 ('0401',
  'Agriculture, forestry, fisheries and allied sciences',
  0.9224274182332315),
 ('0402', 'Veterinary sciences', 0.8119142782937349),
 ('0499',
  'Other agricultural, veterinary and food sciences',
  0.5338588501127698),
 ('0601', 'History and archaeology', 0.9824288411468907)]

In [46]:

normalize_rows = np.zeros((42,42))
for i in range(42):
    normalize_rows[i,i] = df.iloc[i,i]/max(df.iloc[i,:])
    for j in range(42):
        if i<j:
            normalize_rows[i,j]=df.iloc[i,j]/max(df.iloc[i,:])
        elif i>j:
            normalize_rows[i,j]=df.iloc[i,j]/max(df.iloc[i,:])

np.diag(normalize_rows)

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.3783499 , 0.04729758, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.84222379,
       0.34642909, 1.        , 0.70631747, 0.44189963, 1.        ,
       0.5347105 , 1.        , 0.41319696, 0.05769392, 1.        ,
       0.59274512, 0.05700757, 1.        , 1.        , 0.97815522,
       1.        , 1.        , 1.        , 0.2761913 , 1.        ,
       0.22548165, 1.        , 1.        , 1.        , 1.        ,
       0.18787831, 0.52643853])

In [47]:
nz=np.nonzero(np.diag(normalize_rows)-1)
[(discipline_codes[i], discipline_names[i], np.diag(normalize_rows)[i]) for i in list(nz[0])]

[('0107', 'Environmental sciences', 0.3783499007081679),
 ('0199', 'Other natural sciences', 0.047297580015674696),
 ('0207',
  'Biotechnology, bio-engineering and biosystems engineering',
  0.8422237861982143),
 ('0208',
  'Computer engineering, information technology and mathematical engineering',
  0.346429089157201),
 ('0301', 'Basic sciences', 0.7063174735433346),
 ('0302', 'Clinical sciences', 0.4418996301773648),
 ('0304', 'Paramedical sciences', 0.5347105011339955),
 ('0306', 'Translational sciences', 0.41319696153586616),
 ('0399', 'Other medical and health sciences', 0.05769392128873175),
 ('0402', 'Veterinary sciences', 0.5927451237338953),
 ('0499',
  'Other agricultural, veterinary and food sciences',
  0.05700756825189527),
 ('0503', 'Pedagogical and educational sciences', 0.9781552211365655),
 ('0507', 'Social and economic geography', 0.2761913009089298),
 ('0599', 'Other social sciences', 0.22548164883716362),
 ('0699', 'Other humanities and the arts', 0.187878307927476