In [43]:
import pandas as pd
import numpy as np
from scipy.optimize import linprog
from ast import literal_eval
import random 

import ast
def from_np_array(array_string):
    array_string = ','.join(array_string.replace('[ ', '[').split())
    return np.array(ast.literal_eval(array_string))

In [44]:
# load distance matrix M (between disciplines)
path = r'C:\Users\lucp11051\Documents\Jupyter_notebooks\2_Discipline_distances/'

count_type = 'citation_flow'
data = 'matrix15'
# count_type = 'disc_in_a_person'
# data = 'pub_2014'

M = np.loadtxt(path + 'cosine_distance_matrix_' + count_type + data+ '.txt')

In [45]:
number = '0'
string1 = ''
vector_filename = (number + string1 + 'vectors_df.csv')


string = ''
df = pd.read_csv(vector_filename, converters={'Profile': from_np_array, 'Organisations':from_np_array, 
                                                'Projects' + string: from_np_array, 'Coauthors Projects'+ string:from_np_array,
                                                'Publications'+ string: from_np_array, 'Coauthors Publications'+ string:from_np_array})
df['Profile count'] = df['Profile count'].apply(lambda x: literal_eval(x))
df['Organisations count'] = df['Organisations count'].apply(lambda x: literal_eval(x))

df['Projects' + string + ' count'] = df['Projects' + string + ' count'].apply(lambda x: literal_eval(x))
df['Publications' + string + ' count'] = df['Publications' + string + ' count'].apply(lambda x: literal_eval(x))
df['Coauthors Projects' + string + ' count'] = df['Coauthors Projects' + string + ' count'].apply(lambda x: literal_eval(x))
df['Coauthors Publications' + string + ' count'] = df['Coauthors Publications' + string + ' count'].apply(lambda x: literal_eval(x))




# normalize all discipline vectors
def normalize(array):
    norm = array.sum()
    if norm == 0:
        return array
    else:
        normed=array/norm
        if normed.sum() == 1:
            return normed
        else:
            idx=random.choice(np.nonzero(normed)[0])
            normed[idx]=normed[idx]-(normed.sum()-1)
            return normed
for j1 in range(1,2*6,2):
    df.iloc[:,j1]=df.iloc[:,j1].apply(lambda x: normalize(x))



if string1 ==  'weighted_':
        weighted_vectors=df
else:
    vectors=df

df

ID  \
0   e011bd37-a5a1-46af-bf93-cf0a36b66ab5   
1   8834112c-33f1-4ee6-8a34-9c09a7b71535   
2   b73e0e47-ad11-4ce7-a065-2993e6c3b602   
3   f19619e2-340d-47ef-9792-35d2436febc4   
4   45230f30-5ba1-4ba1-a305-1307392c1cc1   
..                                   ...   
59  6c4f337a-6fac-41fc-9224-dc0ccbdeeebb   
60  4b74615b-d701-4448-a191-cb19436ee4cb   
61  b6fd60a4-c095-43ed-9743-67cd091db492   
62  37b7164d-6bd4-470b-98d5-33b349dfd2b5   
63  64b0cfc6-e0a3-4efd-8576-480f849dec0d   

                                              Profile Profile count  \
0   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
1   [0.0, 0.0, 0.0, 0.05, 0.0, 0.25, 0.0, 0.0, 0.0...        (1, 1)   
2   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...      (0.0, 1)   
3   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
4   [0.0, 0.0, 0.0, 0.0, 0.41666667, 0.0, 0.0, 0.0...        (1, 1)   
..                                                ...           ...   
59  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...        (1, 1)   
60  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
61  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
62  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
63  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   

                                        Organisations  \
0   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1   [0.0, 0.0, 0.0, 0.3333333333333333, 0.0, 0.333...   
2   [0.0, 0.0, 0.031249999687500005, 0.0, 0.322916...   
3   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, ...   
..                                                ...   
59  [0.0, 0.0, 0.0, 0.0, 0.0, 0.66666667, 0.0, 0.0...   
60  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
61  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
62  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
63  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

        Organisations count  \
0                    (1, 2)   
1                    (1, 3)   
2   (0.6666666666666667, 3)   
3                    (1, 1)   
4                    (1, 2)   
..                      ...   
59                   (1, 1)   
60                   (1, 4)   
61  (0.8333333333333334, 6)   
62                (0.75, 4)   
63  (0.8333333333333334, 6)   

                                             Projects  \
0   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1   [0.0, 0.0009671199806576005, 0.0, 0.0015197599...   
2   [0.03571428928571422, 0.0, 0.0, 0.035714289285...   
3   [0.0, 0.0, 0.0, 0.0, 0.0, 0.016666669833333304...   
4   [0.0, 0.0, 0.0, 0.0, 0.13684211, 0.03508772, 0...   
..                                                ...   
59  [0.0, 0.0, 0.0, 0.03576657, 0.0, 0.46760667, 0...   
60  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.016...   
61  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
62  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
63  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

              Projects count  \
0                     (1, 1)   
1   (0.9591836734693877, 49)   
2                     (1, 7)   
3                    (1, 30)   
4                     (1, 3)   
..                       ...   
59  (0.9166666666666666, 24)   
60  (0.9655172413793104, 29)   
61                    (1, 6)   
62                    (1, 3)   
63                    (1, 6)   

                                   Coauthors Projects  \
0   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1   [0.025925929740740705, 0.014814809851851901, 0...   
2   [0.0, 0.0, 0.006944439930555601, 0.00529100994...   
3   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.017...   
4   [0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.19166667, 0.0...   
..                                                ...   
59  [0.004536000000000001, 0.053081920000000005, 0...   
60  [0.0, 0.0, 0.04444444, 0.0, 0.0, 0.0, 0.0, 0.0...   
61  [0.0, 0.0, 

In [59]:
df.head(50)

ID  \
0   e011bd37-a5a1-46af-bf93-cf0a36b66ab5   
1   8834112c-33f1-4ee6-8a34-9c09a7b71535   
2   b73e0e47-ad11-4ce7-a065-2993e6c3b602   
3   f19619e2-340d-47ef-9792-35d2436febc4   
4   45230f30-5ba1-4ba1-a305-1307392c1cc1   
5   3de615bf-4167-4fa5-a4d3-0dac8248798a   
6   05e00835-520a-4d3b-8e53-fbe03c1e43c7   
7   acb40a5f-ab6c-4759-90b2-7f2bc628d4a4   
8   d86af692-304d-42dd-bb1f-86d0113be027   
9   e739bf7a-76c2-4e6e-8b6e-4dcf863be95f   
10  86690a80-d34d-4672-b776-265a498d042b   
11  8c662e7b-3e22-4f37-bc2f-a4c7f8593181   
12  68704dd4-d54f-4b74-b9fc-bfd6848d0ba4   
13  56ac1881-71e5-40bd-b091-c03772e3d5f0   
14  8d75503c-b197-42ff-97a2-ff3ca483bc49   
15  de9b5279-ca23-4f12-a7b7-c914440879f0   
16  24e9ba01-07dc-4123-af67-19e82f5fc108   
17  2e1cb018-8750-4c8e-a23b-a5244883a5a6   
18  01e593f8-51cb-47e8-a024-9d5e1e9339d4   
19  88300587-3e99-4017-8d5b-7b3b38a490bd   
20  c4058400-b35e-4611-96d2-635bb27c7af8   
21  c665e5a5-8c68-4c38-901e-b9b32f62501b   
22  5c726ba8-6bc6-4beb-b095-eecb63c7e506   
23  8d991f4d-1e5d-46e7-befa-a009b746cbaa   
24  4c814219-01a5-496d-9b71-7307705d3a9c   
25  6e4510f0-4ac4-41e7-87b0-4ea6eb8f6333   
26  205de141-a729-45e7-a2cf-7b787b757d0a   
27  0233b56f-e2e3-4beb-b60c-5a82a10909d7   
28  5b7d2065-1630-4472-a996-d52205dc2fe4   
29  5c25d7ce-5b1d-4980-956a-97b2c63d3322   
30  42b73d6c-a4a4-4d1b-9ac2-1b304afe9d58   
31  98515a4c-85bc-4a1f-92f1-220985660859   
32  425fd3a0-74f2-4685-b880-955d802195a5   
33  5b652de3-41b8-4a25-81a1-e036dfb8530f   
34  05a541ad-dee5-4a87-a803-32850fe4c25e   
35  2660291d-dbbd-440e-9e87-d121cca8617e   
36  352cf218-7673-40be-8adf-91d7fae84771   
37  60772b54-f741-41e0-b516-e645c3778fcc   
38  784fc58b-f661-4827-857c-5a03ede35aa2   
39  4f788022-78dd-41e2-b629-f7edc41cbc26   
40  fddd208f-e0ab-4121-8ac6-42e59c69ed55   
41  c6ccba75-72a1-4696-a38c-b9bcbd42cbfd   
42  fa38018f-b7fe-457f-b039-ef79636868f1   
43  0ba45b57-44c9-4c02-b126-6f240d9166e9   
44  90b3592e-fa1d-4db8-bfc3-8062cce35f3e   
45  5b420256-82a4-44da-b7bd-e3ad53a5450c   
46  5be4f4a9-8e23-4b68-b065-b72cf2d797c2   
47  dc6635a5-56db-498e-8818-58a5d70c4016   
48  3474dfc8-5d66-43c4-b6a4-0fa8a1fcdf18   
49  59416db9-5d0c-463d-a025-871b1d1be1f1   

                                              Profile Profile count  \
0   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
1   [0.0, 0.0, 0.0, 0.05, 0.0, 0.25, 0.0, 0.0, 0.0...        (1, 1)   
2   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...      (0.0, 1)   
3   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
4   [0.0, 0.0, 0.0, 0.0, 0.41666667, 0.0, 0.0, 0.0...        (1, 1)   
5   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, ...        (1, 1)   
6   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
7   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
8   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
9   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
10  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
11  [0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.2, 0.0, 0.1, ...        (1, 1)   
12  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, ...        (1, 1)   
13  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
14  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, ...        (1, 1)   
15  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
16  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
17  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
18  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
19  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
20  [0.0, 0.0, 0.85714286, 0.0, 0.0, 0.0, 0.0, 0.0...        (1, 1)   
21  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
22  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
23  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...        (1, 1)   
24  [0.0, 0.0, 0.0

In [46]:
# Transform sparse arrays p,q and M to dense arrays by deleting entries (disciplines) which are zero for both p and q.
def discipline_compressor(p,q,M):

    zero_entries=[]

    for i in range(len(p)):
        if p[i]==0 and q[i]==0:
            zero_entries.append(i)
            
    zero_entries.sort(reverse=True)
    p_dense=p.copy()
    q_dense=q.copy()
    M_dense=M.copy()

    for j in zero_entries:
        M_dense=np.delete(M_dense, j, 1)
        M_dense=np.delete(M_dense, j, 0)
        p_dense= np.delete(p_dense,j)
        q_dense= np.delete(q_dense,j)
    
    return p_dense,q_dense,M_dense

def constraint_maker(n):
    constraint_matrix=np.zeros((2*n,n**2))

    for i in range(n):
        constraint_matrix[i][i*n:i*n+n]=np.ones(n)
        for j in range(n):
            constraint_matrix[i+n][n*j+i]=1

    constraint_matrix=np.delete(constraint_matrix,0,0) #delete first (redundent) row to get full row rank
    return constraint_matrix

def wasserstein(p,q,M):
    p_dense,q_dense,M_dense=discipline_compressor(p,q,M)

    obj = M_dense.flatten()


    lhs_eq = constraint_maker(len(p_dense))  
    rhs_eq = np.append(p_dense,q_dense)[1:]      

    opt = linprog(c=obj, 
                  A_eq=lhs_eq, b_eq=rhs_eq, 
                  method="revised simplex")
    return opt.fun

In [47]:
if string1 == 'weighted_':
    vectors_df = weighted_vectors
elif string1 == '':
    vectors_df = vectors

In [48]:
#calculate the mean distances between types of discipline vectors
compare_df=pd.DataFrame(columns=vectors_df.columns, index= vectors_df.columns)
for j1 in range(1,2*6,2):
    for j2 in range(1,2*6,2):
        if j2<j1:
            continue
        distances = np.array([])
        for i in range(vectors_df.shape[0]):            
            p=vectors_df.iloc[i,j1]
            q=vectors_df.iloc[i,j2]
            if p.sum()==1 and q.sum()==1:
                dist = wasserstein(p,q,M)
                distances=np.append(distances, [dist])
        compare_df.iloc[j1,j2]=np.median(distances)
        compare_df.iloc[j2,j1]=np.median(distances)

compare_df=compare_df.dropna(thresh=1)
compare_df=compare_df.dropna(axis='columns')

if string1 == 'weighted_':
    weigthed_compare = compare_df
elif string1 == '':
    compare = compare_df

In [49]:
compare

Profile Organisations     Projects  \
Profile                        0      0.141019     0.201805   
Organisations           0.141019             0      0.20592   
Projects                0.201805       0.20592  9.82892e-18   
Coauthors Projects      0.258561      0.252368     0.146841   
Publications            0.342848      0.376834     0.249605   
Coauthors Publications   0.24246      0.227896     0.160395   

                       Coauthors Projects Publications Coauthors Publications  
Profile                          0.258561     0.342848                0.24246  
Organisations                    0.252368     0.376834               0.227896  
Projects                         0.146841     0.249605               0.160395  
Coauthors Projects            1.94038e-17     0.302414               0.127148  
Publications                     0.302414  1.82656e-17               0.304124  
Coauthors Publications           0.127148     0.304124            2.93379e-17

In [50]:
distance=[]
for i in range(vectors_df.shape[0]):            
    p=vectors_df.loc[i,'Profile']
    q=vectors_df.loc[i,'Organisations']
    if p.sum()==1 and q.sum()==1:
        dist = wasserstein(p,q,M)
#         print(dist, i)
        distance.append(dist)
    else:
        print(p.sum(),q.sum())
np.mean(distance)

0.0 1.0
0.0 1.0
0.0 0.0
0.0 1.0


0.22166528552940018

In [51]:
vectors.iloc[5]

ID                                           3de615bf-4167-4fa5-a4d3-0dac8248798a
Profile                         [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, ...
Profile count                                                              (1, 1)
Organisations                   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, ...
Organisations count                                                        (1, 3)
Projects                        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.557...
Projects count                                                            (1, 12)
Coauthors Projects              [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.556...
Coauthors Projects count                                 (0.8666666666666667, 15)
Publications                    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
Publications count                                       (0.3653846153846153, 52)
Coauthors Publications          [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.578...
Coauthors Public

In [52]:
r = np.zeros(6)
s = [0.25,0.25,0.125,0.125,0.125,0.125]
for j in range(6):
        r[j] =s[j]

In [53]:
#s = significance,importance, q = quality (of available information), r = rest or remainder part that is not initially 'filled',
#
#

def construct_alphas(person, s = [0.25,0.25,0.125,0.125,0.125,0.125]):
    alpha = np.zeros(6)
    r = np.zeros(6)
    q = quality_maker(person)
    if np.count_nonzero(q)<2:
        if q.sum()==0:
            return q
        else:
            return q/q.sum()
    for j in range(6):
        r[j] = s[j]*(1-q[j])
    
    for k in range(6):
        beta=0
        for j in range(6):
            
            if j == k:
                continue
            denominator = 0
            for i in range(6):
                if i == j:
                    continue
                denominator=denominator + q[i]*s[i]
            beta=beta+(q[k]*s[k]*r[j])/denominator            
                                
        alpha[k]=q[k]*s[k]+beta
    return alpha

def construct_alphas_by_normalization(person, s = [0.25,0.25,0.125,0.125,0.125,0.125]):
    
    q = quality_maker(person)
    alpha=q*np.array(s)
    if alpha.sum()==0:
        return alpha
    else:
        return alpha/alpha.sum()
    
def quality_maker(person):
    q = np.zeros(6)
    q[0]=person['Profile count'][0]
    q[1]=person['Organisations count'][0]
    q[2]=min(1,person['Projects count'][1]/4)*person['Projects count'][0]
    q[3]=min(1,person['Projects count'][1]/4)*min(1,person['Coauthors Projects count'][1]/6)*person['Coauthors Projects count'][0]
    q[4]=min(1,person['Publications count'][1]/10)*person['Publications count'][0]
    q[5]=min(1,person['Publications count'][1]/10)*min(1,person['Coauthors Publications count'][1]/20)*person['Coauthors Publications count'][0]
    return q

quality_maker(vectors.iloc[5]),construct_alphas(vectors.iloc[5], s = [0.25,0.25,0.125,0.125,0.125,0.125]),\
construct_alphas_by_normalization(vectors.iloc[5], s = [0.25,0.25,0.125,0.125,0.125,0.125])

(array([1.        , 1.        , 1.        , 0.86666667, 0.36538462,
        0.30909091]),
 array([0.30928   , 0.30928   , 0.15464   , 0.13147582, 0.05180975,
        0.04351444]),
 array([0.305757  , 0.305757  , 0.1528785 , 0.1324947 , 0.05585945,
        0.04725335]))

In [54]:
alpha=[]
alphanorm=[]
quality =[]
for i in range(vectors_df.shape[0]):
    alpha.append(construct_alphas(vectors_df.iloc[i], s = [0.25,0.25,0.125,0.125,0.125,0.125]))
    alphanorm.append(construct_alphas_by_normalization(vectors_df.iloc[i], s = [0.25,0.25,0.125,0.125,0.125,0.125]))
    quality.append(quality_maker(vectors_df.iloc[i]))

In [55]:
np.median(np.array(alpha),axis=0),np.median(np.array(alphanorm),axis=0), np.median(np.array(quality),axis=0)

(array([0.30544771, 0.30356497, 0.14384242, 0.14168364, 0.05287042,
        0.05790784]),
 array([0.30310237, 0.30089512, 0.14281407, 0.14075967, 0.05696919,
        0.06205219]),
 array([1.        , 1.        , 0.97638889, 0.94581771, 0.35365041,
        0.41139866]))

In [56]:
np.mean(np.array(alpha),axis=0),np.mean(np.array(alphanorm),axis=0), np.mean(np.array(quality),axis=0)

(array([0.30528561, 0.32162022, 0.14056815, 0.1219266 , 0.05192769,
        0.05867173]),
 array([0.30139076, 0.31991994, 0.14098783, 0.12097167, 0.05504714,
        0.06168267]),
 array([0.9375    , 0.94986979, 0.82575283, 0.76393306, 0.35483128,
        0.38582094]))

In [57]:
col=['ID','Profile','Organisations', 'Projects', 'Coauthors Projects','Publications', 'Coauthors Publications']

if string1 == 'weighted_':
    weighted_vectors_with_alphas=weighted_vectors[col].copy()
    weighted_vectors_with_alphas['Alphas']=alpha
    weighted_vectors_with_alphas.to_csv(number + 'weighted_vectors_with_alphas.csv', index=False, float_format='%s')
elif string1 == '':  
    vectors_with_alphas=vectors[col].copy()
    vectors_with_alphas['Alphas']=alpha
    vectors_with_alphas.to_csv(number + 'vectors_with_alphas.csv', index=False)

In [58]:
vectors_with_alphas

ID  \
0   e011bd37-a5a1-46af-bf93-cf0a36b66ab5   
1   8834112c-33f1-4ee6-8a34-9c09a7b71535   
2   b73e0e47-ad11-4ce7-a065-2993e6c3b602   
3   f19619e2-340d-47ef-9792-35d2436febc4   
4   45230f30-5ba1-4ba1-a305-1307392c1cc1   
..                                   ...   
59  6c4f337a-6fac-41fc-9224-dc0ccbdeeebb   
60  4b74615b-d701-4448-a191-cb19436ee4cb   
61  b6fd60a4-c095-43ed-9743-67cd091db492   
62  37b7164d-6bd4-470b-98d5-33b349dfd2b5   
63  64b0cfc6-e0a3-4efd-8576-480f849dec0d   

                                              Profile  \
0   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1   [0.0, 0.0, 0.0, 0.05, 0.0, 0.25, 0.0, 0.0, 0.0...   
2   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4   [0.0, 0.0, 0.0, 0.0, 0.41666667, 0.0, 0.0, 0.0...   
..                                                ...   
59  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...   
60  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
61  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
62  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
63  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                        Organisations  \
0   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1   [0.0, 0.0, 0.0, 0.3333333333333333, 0.0, 0.333...   
2   [0.0, 0.0, 0.031249999687500005, 0.0, 0.322916...   
3   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, ...   
..                                                ...   
59  [0.0, 0.0, 0.0, 0.0, 0.0, 0.66666667, 0.0, 0.0...   
60  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
61  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
62  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
63  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                             Projects  \
0   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1   [0.0, 0.0009671199806576005, 0.0, 0.0015197599...   
2   [0.03571428928571422, 0.0, 0.0, 0.035714289285...   
3   [0.0, 0.0, 0.0, 0.0, 0.0, 0.016666669833333304...   
4   [0.0, 0.0, 0.0, 0.0, 0.13684211, 0.03508772, 0...   
..                                                ...   
59  [0.0, 0.0, 0.0, 0.03576657, 0.0, 0.46760667, 0...   
60  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.016...   
61  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
62  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
63  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                   Coauthors Projects  \
0   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1   [0.025925929740740705, 0.014814809851851901, 0...   
2   [0.0, 0.0, 0.006944439930555601, 0.00529100994...   
3   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.017...   
4   [0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.19166667, 0.0...   
..                                                ...   
59  [0.004536000000000001, 0.053081920000000005, 0...   
60  [0.0, 0.0, 0.04444444, 0.0, 0.0, 0.0, 0.0, 0.0...   
61  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
62  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
63  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                         Publications  \
0   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1   [0.0, 0.0, 0.01904762, 0.06666667, 0.0, 0.1047...   
2   [0.0, 0.0, 0.0, 0.0, 0.01851851962962961, 0.0,...   
3   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4   [0.0, 0.0, 0.0, 0.0, 0.03076923, 0.0, 0.111538...   
..                                                ...   
59  [0.0, 0.0, 0.0, 0.03639847, 0.0, 0.57088123, 0...   
60  [0.0, 0.0, 0.16909721830902782, 0.198263888017...   
61  [0.0, 0.0, 0.0, 0.0, 0.0, 0.10984848000000001,...   
62  [0.0, 0.0, 0.0, 0.0, 0.0, 0.18333333, 0.0, 0.0...   
63  [0.0, 0.0, 0.0, 0.0, 0.0, 0.10984848000000001,...   

                               Coauthors Publications  \
0   [0.0, 0.0, 0.0, 0.0, 0.